import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import SotifyContext from "@/context/SotifyContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SotifyContext>{children}</SotifyContext>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
