"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import SotifyContext from "@/context/SotifyContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <SotifyContext>{children}</SotifyContext>
        </AuthProvider>
      </body>
    </html>
  );
}
